apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7aiq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0001-tenant/tkwch-fix-0075-0001-app/devfile-sample-7aiq@sha256:b1abc6bc236d4b3852e78f2e454a2c533b1a88f325b523716783590964bcfd5f
        name: my-nodejs
        resources: {}
status: {}
